POST http://localhost:3333/events
Content-Type: application/json

{
  "title": "Unite Summit",
  "details": "Description",
  "maximumAttendees": 100
}

###

POST http://localhost:3333/events/feebfc7f-3cf8-476d-aae1-cc829aed8978/attendees
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john@gmail.com"
}

###

GET http://localhost:3333/events/feebfc7f-3cf8-476d-aae1-cc829aed8978

###

GET http://localhost:3333/attendees/1/badge

###

GET http://localhost:3333/attendees/1/check-in

###

GET http://localhost:3333/events/feebfc7f-3cf8-476d-aae1-cc829aed8978/attendees?query=john